// Add other images path here

const path = "/images/shared"

export const images = {
    logo: `${path}/logo_main.avif`,
    stickyLogo: `${path}/logo-small-white.webp`,
    product: `${path}/product.jpg`,
    corporate: `${path}/corporate1.webp`,
    specialOffer: `${path}/footer_get_special_offer.webp`,
    americanExpress: `${path}/american-express.svg`,
    applePay: `${path}/apple-pay.svg`,
    masterCard: `${path}/master-card.svg`,
    payPal: `${path}/pay-pal.svg`,
    shopPay: `${path}/shop-pay.svg`,
    unionPay: `${path}/union-pay.svg`,
    visa: `${path}/visa.svg`,
    events: `${path}/events1.webp`,
    feedback1: `${path}/feedback1.webp`,
    feedback2: `${path}/feedback2.jpg`,
    feedback3: `${path}/feedback3.webp`,
    aboutUs: `${path}/about_us1.jpg`,
    howItWork: `${path}/side-img-how-it-work.webp`,
    contact: `${path}/contact.webp`,
    home1: `${path}/home1.webp`,
    home2: `${path}/home2.webp`,
    home3: `${path}/home3.webp`,
    home4: `${path}/home4.webp`,
    home5: `${path}/home5.webp`,
    home6: `${path}/home6.webp`,
    home7: `${path}/home7.webp`,
    home8: `${path}/home8.webp`,
    home9: `${path}/home9.webp`,
    home10: `${path}/home10.webp`,
    home11: `${path}/home11.webp`,
    home12: `${path}/home12.webp`,
    home13: `${path}/home13.webp`,
    home14: `${path}/home14.webp`,
  };